LM01:
  x: -4.0
  y: 4.0
  yaw: 0.0
LM02:
  x: -2.0
  y: 4.0
  yaw: 0.0
LM03:
  x: 0.0
  y: 4.0
  yaw: 0.0
LM04:
  x: 2.0
  y: 4.0
  yaw: 0.0
LM05:
  x: 4.0
  y: 4.0
  yaw: 0.0
LM06:
  x: -4.0
  y: 2.0
  yaw: 0.0
LM07:
  x: -2.0
  y: 2.0
  yaw: 0.0
LM08:
  x: 0.0
  y: 2.0
  yaw: 0.0
LM09:
  x: 2.0
  y: 2.0
  yaw: 0.0
LM10:
  x: 4.0
  y: 2.0
  yaw: 0.0
LM11:
  x: -4.0
  y: 0.0
  yaw: 0.0
LM12:
  x: -2.0
  y: 0.0
  yaw: 0.0
LM13:
  x: 0.0
  y: 0.0
  yaw: 0.0
LM14:
  x: 2.0
  y: 0.0
  yaw: 0.0
LM15:
  x: 4.0
  y: 0.0
  yaw: 0.0
LM16:
  x: -4.0
  y: -2.0
  yaw: 0.0
LM17:
  x: -2.0
  y: -2.0
  yaw: 0.0
LM18:
  x: 0.0
  y: -2.0
  yaw: 0.0
LM19:
  x: 2.0
  y: -2.0
  yaw: 0.0
LM20:
  x: 4.0
  y: -2.0
  yaw: 0.0
LM21:
  x: -4.0
  y: -4.0
  yaw: 0.0
LM22:
  x: -2.0
  y: -4.0
  yaw: 0.0
LM23:
  x: 0.0
  y: -4.0
  yaw: 0.0
LM24:
  x: 2.0
  y: -4.0
  yaw: 0.0
LM25:
  x: 4.0
  y: -4.0
  yaw: 0.0
