LM1:
  x: -2.0
  y: 2.0
  yaw: 0.0

LM2:
  x: 0.0
  y: 2.0
  yaw: 0.0

LM3:
  x: 2.0
  y: 2.0
  yaw: 0.0

LM4:
  x: -2.0
  y: 0.0
  yaw: 0.0

LM5:
  x: 0.0
  y: 0.0
  yaw: 0.0

LM6:
  x: 2.0
  y: 0.0
  yaw: 0.0

LM7:
  x: -2.0
  y: -2.0
  yaw: 0.0

LM8:
  x: 0.0
  y: -2.0
  yaw: 0.0

LM9:
  x: 2.0
  y: -2.0
  yaw: 0.0